image: node:latest

before_script:
  - mkdir -p ~/.ssh && echo -e "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa
#  - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - npm install --unsafe-perm
  - git clone https://github.com/zazuko/ssz-views.git && cd ssz-views && npm install
  - cd $CI_PROJECT_DIR

cache:
  paths:
    - node_modules/

pipeline_prod:
  only:
    - master
#   - develop
  tags:
    - medium
  environment:
    name: PROD
  script:
    - ./scripts/main.sh

pipeline_int:
  only:
    - develop-DISABLE
  tags:
    - medium
  except:
    variables:
      - $RELEASE == "zazuko"
  environment:
    name: INT
  script:
    - ./scripts/main.sh

pipeline_test:
  only:
    - develop
#    variables:
#      - $RELEASE == "zazuko"
  tags:
    - medium
  environment:
    name: TEST
  script:
      - ./scripts/main.sh